# Generated by Django 5.0.7 on 2024-08-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EggCyclesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FriendShipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthRateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('heigth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weigth', models.DecimalField(decimal_places=2, max_digits=4)),
                ('abilities', models.ManyToManyField(related_name='abilities', to='pokemon.ability')),
                ('hidden_ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_ability', to='pokemon.ability')),
                ('types', models.ManyToManyField(related_name='types', to='pokemon.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderless', models.BooleanField(blank=True, default=False)),
                ('male', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('female', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('egg_cycles_value', models.PositiveIntegerField()),
                ('egg_cycles_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_cycles_category', to='pokemon.eggcyclescategory')),
                ('egg_groups', models.ManyToManyField(related_name='egg_groups', to='pokemon.egggroup')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('sp_atk', models.PositiveIntegerField()),
                ('sp_def', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemon.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokedexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex_entries', to='pokemon.pokemon')),
                ('pokemon_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pokemon_entries', to='pokemon.pokemongame')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_exp', models.PositiveIntegerField()),
                ('catch_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('base_friendship', models.PositiveIntegerField()),
                ('friendship_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendship_category', to='pokemon.friendshipcategory')),
                ('growth_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growth_rate', to='pokemon.growthratecategory')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traning', to='pokemon.pokemon')),
            ],
        ),
    ]
