# Generated by Django 5.0.7 on 2024-08-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ability',
            table='abilities',
        ),
        migrations.AlterModelTable(
            name='basestats',
            table='base_stats',
        ),
        migrations.AlterModelTable(
            name='breeding',
            table='breeding_stats',
        ),
        migrations.AlterModelTable(
            name='eggcyclescategory',
            table='egg_cycles_categories',
        ),
        migrations.AlterModelTable(
            name='egggroup',
            table='egg_groups',
        ),
        migrations.AlterModelTable(
            name='friendshipcategory',
            table='friendship_categories',
        ),
        migrations.AlterModelTable(
            name='growthratecategory',
            table='growth_rate_category',
        ),
        migrations.AlterModelTable(
            name='pokedexentry',
            table='pokedex_entries',
        ),
        migrations.AlterModelTable(
            name='pokemon',
            table='pokemons',
        ),
        migrations.AlterModelTable(
            name='pokemongame',
            table='pokemon_games',
        ),
        migrations.AlterModelTable(
            name='pokemontype',
            table='types',
        ),
        migrations.AlterModelTable(
            name='training',
            table='training_stats',
        ),
    ]
